# Generated by Django 5.1.4 on 2026-01-08 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptwriter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.PositiveIntegerField()),
                ('setting', models.CharField(help_text='Scene location and time', max_length=500)),
                ('goal', models.TextField(help_text='What the scene aims to accomplish')),
                ('tension', models.TextField(help_text='Source of conflict or tension')),
                ('tone', models.CharField(blank=True, help_text='Specific tone for this scene', max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scene_number'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('personality', models.TextField(blank=True, help_text='Character personality traits')),
                ('goals', models.TextField(blank=True, help_text='Character goals and motivations')),
                ('voice', models.TextField(blank=True, help_text='Character voice and speaking style')),
                ('backstory', models.TextField(blank=True, help_text='Character background')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('scifi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('other', 'Other')], default='drama', max_length=50)),
                ('tone', models.CharField(choices=[('light', 'Light'), ('serious', 'Serious'), ('dark', 'Dark'), ('comedic', 'Comedic'), ('dramatic', 'Dramatic'), ('suspenseful', 'Suspenseful'), ('inspirational', 'Inspirational')], default='dramatic', max_length=50)),
                ('logline', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='scripts', to='scriptwriter.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('job_type', models.CharField(choices=[('script_generation', 'Script Generation'), ('scene_generation', 'Scene Generation'), ('script_refinement', 'Script Refinement')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prompt', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scriptwriter.scene')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scriptwriter.script')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('notes', models.TextField(blank=True, help_text='Notes about this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scriptwriter.script')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('script', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='script_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scriptwriter.scriptversion'),
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('script_version', 'scene_number')},
        ),
    ]
